// <auto-generated />
namespace OnlineAppointment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Starting5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Starting5));
        
        string IMigrationMetadata.Id
        {
            get { return "201907271634376_Starting5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
